# Generated by Django 3.1.5 on 2021-02-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='icon',
            field=models.CharField(default='some-icom', max_length=20, verbose_name='Icon of category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='icon',
            field=models.CharField(default='some-icon', max_length=20, verbose_name='Icon of category'),
            preserve_default=False,
        ),
    ]
