# Generated by Django 3.1.5 on 2021-02-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
    ]
