# Generated by Django 3.1.5 on 2021-02-24 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20210223_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_transaction',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='related_income',
        ),
        migrations.RemoveField(
            model_name='income',
            name='is_transaction',
        ),
        migrations.AddField(
            model_name='expense',
            name='is_transfer',
            field=models.BooleanField(default=False, verbose_name='Is transfer?'),
        ),
        migrations.AddField(
            model_name='income',
            name='is_transfer',
            field=models.BooleanField(default=False, verbose_name='Is transfer?'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Rate')),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='transaction.income', verbose_name='Expense')),
                ('income', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='transaction.income', verbose_name='Income')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
            },
        ),
    ]
