# Generated by Django 3.1.5 on 2021-03-01 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transfer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='expense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='transaction.expense', verbose_name='Expense'),
        ),
    ]
