# Generated by Django 3.1.3 on 2021-01-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'verbose_name': 'Income Category', 'verbose_name_plural': 'Income Categories'},
        ),
    ]
