# Generated by Django 3.1.5 on 2021-01-25 17:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20210125_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='action.expensecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='action.incomecategory', verbose_name='Category'),
        ),
    ]
