# Generated by Django 3.1.5 on 2021-01-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20210116_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='related_income',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_expense', to='action.income', verbose_name='Related Income'),
        ),
    ]
