# Generated by Django 3.1.3 on 2021-01-13 13:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20210113_1032'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='action',
            managers=[
                ('incomes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='expense',
            managers=[
                ('incomes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='income',
            managers=[
                ('incomes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='is_transaction',
            field=models.BooleanField(default=False, verbose_name='Is transaction?'),
        ),
    ]
