# Generated by Django 3.1.3 on 2021-01-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_auto_20210113_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-date', 'name'], 'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelManagers(
            name='action',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='expense',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='income',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='transaction_rel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.expense', verbose_name='Transaction'),
        ),
    ]
