version: '3.7'

services:
  django:
    container_name: my_money_django
    build: ./backend
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - django_static_volume:/usr/src/backend/static/
    expose:
      - 8000
    env_file:
      - ./backend/.env
    depends_on: 
      - db
  db:
    container_name: my_money_db
    image: postgres:12.0-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=prog-serhii
      - POSTGRES_DB=mymoney
  react:
    container_name: my_money_react
    build: ./frontend
    volumes: 
      - react_static_volume:/usr/src/frontend/build/static
    expose: 
      - 3000
    command: serve -s build -l 3000
    depends_on:
      - django    
  nginx:
    container_name: my_money_nginx
    build: ./nginx
    volumes: 
      - django_static_volume:/usr/src/backend/django_files/static
      - react_static_volume:/usr/src/frontend/react_files/static
    ports:
      - 80:80
    depends_on: 
      - react
  
volumes:
  postgres_data:
  django_static_volume:
  react_static_volume: