# Generated by Django 3.1.5 on 2021-02-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ('-name',), 'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='wallet_type',
        ),
        migrations.AddField(
            model_name='wallet',
            name='icon',
            field=models.CharField(default='', max_length=20, verbose_name='Icon of wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Date of initial balance'),
        ),
    ]
