# Generated by Django 3.1.3 on 2020-11-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('cashe', 'Cashe'), ('card', 'Bank Card')], default='cashe', max_length=10, verbose_name='Type of wallet'),
        ),
    ]
