# Generated by Django 3.1.3 on 2020-11-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_wallet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='logo',
        ),
    ]
