# Generated by Django 3.1.5 on 2021-02-15 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20210215_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='created',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of initial balance'),
        ),
    ]
