# Generated by Django 3.1.3 on 2020-11-13 15:08

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_wallet_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['updated'], 'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='start_balance_currency',
            new_name='initial_balance_currency',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='active',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='start_balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='initial_balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, verbose_name='Initial balance'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
