// template
export const TOGGLE_SIDEBAR = 'TOOGLE_SIDEBAR'

// auth
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS'
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGOUT = 'LOGOUT'

// errors
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

// wallets
export const GET_WALLETS_SUCCESS = 'GET_WALLETS_SUCCESS'
export const GET_WALLETS_FAIL = 'GET_WALLETS_FAIL'
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS'
export const GET_BALANCE_FAIL = 'GET_BALANCE_FAIL'
export const GET_WALLET_DETAIL_SUCCESS = 'GET_WALLET_DETAIL_SUCCESS'
export const GET_WALLET_DETAIL_FAIL = 'GET_WALLET_DETAIL_FAIL'

// dashboard
export const GET_EXCHANGE_RATES = 'GET_EXCHANGE_RATES'
export const GET_EXCHANGE_RATES_SUCCESS = 'GET_EXCHANGE_RATES_SUCCESS'
export const GET_EXCHANGE_RATES_FAIL = 'GET_EXCHANGE_RATES_FAIL'