# Generated by Django 3.1.3 on 2020-12-14 19:17

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_main_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_currency',
            field=djmoney.models.fields.CurrencyField(default='EUR', max_length=3, verbose_name='Main currency'),
        ),
    ]
