# Generated by Django 3.1.3 on 2020-12-14 19:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201214_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currencies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=['EUR'], size=8),
            preserve_default=False,
        ),
    ]
