# Generated by Django 3.1.3 on 2020-12-16 15:58

import apps.user.models
import django.contrib.postgres.fields
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201214_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currencies',
            field=django.contrib.postgres.fields.ArrayField(base_field=djmoney.models.fields.CurrencyField(blank=True, default='EUR', max_length=3, validators=[apps.user.models.currency_code_validator]), blank=True, size=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='main_currency',
            field=djmoney.models.fields.CurrencyField(default='EUR', max_length=3, validators=[apps.user.models.currency_code_validator], verbose_name='Main currency'),
        ),
    ]
